<?php

declare(strict_types=1);

namespace App\Http\Requests\MemoryWall;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Validates the token used to access an existing anonymous upload session.
 */
class UploadSessionRequest extends FormRequest
{
    /**
     * Session ownership is checked by the upload action after validation.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Require the fixed-format token generated by the browser at initialization.
     *
     * @return array<string, array<int, string>>
     */
    public function rules(): array
    {
        return [
            'upload_token' => ['required', 'string', 'size:64', 'regex:/^[a-f0-9]+$/i'],
        ];
    }

    /**
     * Retrieve and cast the validated upload token to a string.
     */
    public function token(): string
    {
        return (string) $this->validated('upload_token');
    }
}
